#DATABASE
mongodb:
  database: "marketplace"
  username: ""
  password: ""
  hostname: "localhost"
  port: 27017
transaction-log-entry-bought: "<gradient:#343124:#654321>Bought: {amount}x {item} for {symbol}{price} from {player}</gradient>"
transaction-log-entry-sold: "<gradient:#343124:#654321>Sold: {amount}x {item} for {symbol}{price} to {player}</gradient>"

black-market-interval: 1 #IN HOURS
gui:
  main:
    title: "<gradient:#343124:#654321>Marketplace [Page {page}]</gradient>"
    next-button:
      label: "<green>Go to page {nextPage}</green>"
      material: GREEN_WOOL
    back-button:
      label: "<red>Go to page {previousPage}</red>"
      material: RED_WOOL
    listing:
      price: "<gold>Price: {price}</gold>"
      player: "<yellow>Seller: {player}</yellow>"
  confirmation:
    title: "<gradient:#123456:#654321>Confirmation</gradient>"
    confirm-button:
      label: "<green>Confirm</green>"
      material: LIME_STAINED_GLASS_PANE
    cancel-button:
      label: "<red>Cancel</red>"
      material: RED_STAINED_GLASS_PANE
